import 'dotenv/config';
import { db, schema } from './index.js';

const recipes = [
  // --- Salad Seasons (7) ---
  {
    name: 'Arugula Salad with Whole-Lemon Vinaigrette',
    source: 'Salad Seasons',
    category: 'side',
    ingredients: [
      { name: 'raw almonds', quantity: '1/3', unit: 'cup' },
      { name: 'lemon (whole, seeded)', quantity: '1', unit: '' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'honey', quantity: '1', unit: 'tsp' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'arugula', quantity: '5', unit: 'oz' },
    ],
    steps: [
      'Toast almonds in a dry skillet over medium heat until fragrant, 3-4 min. Roughly chop.',
      'Cut whole lemon into chunks, remove seeds. Blend lemon, garlic, honey, and olive oil until smooth.',
      'Toss arugula with vinaigrette, top with toasted almonds.',
    ],
    prepTime: '10 min',
    cookTime: '4 min',
    servings: 4,
    macrosPerServing: { calories: 160, protein_g: 3, carbs_g: 6, fat_g: 14 },
    tags: ['anti-inflammatory', 'vegan-adaptable'],
    notes: null,
  },
  {
    name: 'Quick-Pickled Radish Salad',
    source: 'Salad Seasons',
    category: 'side',
    ingredients: [
      { name: 'apple cider vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'cucumbers', quantity: '2', unit: 'medium' },
      { name: 'red radishes', quantity: '6', unit: '' },
      { name: 'watermelon radish', quantity: '1', unit: 'small' },
      { name: 'chives', quantity: '2', unit: 'tbsp' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Whisk ACV, olive oil, and sugar. Thinly slice cucumbers and radishes.',
      'Toss vegetables with dressing, top with chives and dill.',
      'Let rest 30 min for flavors to meld.',
    ],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 4,
    macrosPerServing: { calories: 80, protein_g: 1, carbs_g: 6, fat_g: 7 },
    tags: ['anti-inflammatory', 'vegan', 'batch-prep-friendly'],
    notes: null,
  },
  {
    name: 'Little Gems with Herby Ranch Yogurt',
    source: 'Salad Seasons',
    category: 'side',
    ingredients: [
      { name: 'Greek yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'mayo', quantity: '2', unit: 'tbsp' },
      { name: 'apple cider vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'chives', quantity: '2', unit: 'tbsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
      { name: 'tarragon', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'Little Gem lettuce', quantity: '4', unit: 'heads' },
      { name: 'lemon', quantity: '1', unit: '' },
    ],
    steps: [
      'Blend yogurt, mayo, ACV, herbs, and garlic until smooth.',
      'Halve Little Gems lengthwise, arrange on plate.',
      'Drizzle with ranch yogurt, squeeze lemon over top.',
    ],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 4,
    macrosPerServing: { calories: 110, protein_g: 5, carbs_g: 6, fat_g: 8 },
    tags: ['glucose-friendly'],
    notes: null,
  },
  {
    name: 'Tortellini Salad with Garlic Scape Pesto',
    source: 'Salad Seasons',
    category: 'dinner',
    ingredients: [
      { name: 'garlic scapes', quantity: '1', unit: 'cup' },
      { name: 'pistachios', quantity: '1/3', unit: 'cup' },
      { name: 'olive oil', quantity: '1/3', unit: 'cup' },
      { name: 'Pecorino cheese', quantity: '1/2', unit: 'cup' },
      { name: 'lemon', quantity: '1', unit: '' },
      { name: 'cheese tortellini', quantity: '12', unit: 'oz' },
      { name: 'asparagus', quantity: '1', unit: 'bunch' },
      { name: 'radicchio', quantity: '1', unit: 'small head' },
      { name: 'arugula', quantity: '2', unit: 'cups' },
      { name: 'basil', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Blend garlic scapes, pistachios, olive oil, Pecorino, and lemon juice into pesto.',
      'Cook tortellini and blanch asparagus. Drain and cool slightly.',
      'Toss tortellini, asparagus, radicchio, arugula, and basil with pesto.',
    ],
    prepTime: '15 min',
    cookTime: '10 min',
    servings: 4,
    macrosPerServing: { calories: 420, protein_g: 16, carbs_g: 38, fat_g: 24 },
    tags: ['batch-prep-friendly'],
    notes: null,
  },
  {
    name: 'Warm Spinach-Artichoke Salad with Quinoa Crunchies',
    source: 'Salad Seasons',
    category: 'dinner',
    ingredients: [
      { name: 'quinoa', quantity: '1/2', unit: 'cup' },
      { name: 'artichoke hearts (jarred)', quantity: '1', unit: 'jar (12 oz)' },
      { name: 'baby spinach', quantity: '5', unit: 'oz' },
      { name: 'lemon', quantity: '1', unit: '' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup' },
      { name: 'scallions', quantity: '3', unit: '' },
    ],
    steps: [
      'Cook quinoa until crispy in a dry skillet, stirring often.',
      'Warm artichoke hearts in olive oil. Add spinach to wilt.',
      'Top with crispy quinoa, crumbled feta, scallions, and lemon juice.',
    ],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    macrosPerServing: { calories: 220, protein_g: 10, carbs_g: 28, fat_g: 8 },
    tags: ['anti-inflammatory', 'high-fiber'],
    notes: null,
  },
  {
    name: 'Spicy Smashed Cucumbers with Chickpea Scallion Pancakes',
    source: 'Salad Seasons',
    category: 'dinner',
    ingredients: [
      { name: 'chickpea flour', quantity: '1', unit: 'cup' },
      { name: 'cucumbers', quantity: '2', unit: 'large' },
      { name: 'avocado', quantity: '1', unit: '' },
      { name: 'Asian chili sauce (Huy Fong)', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'sesame seeds', quantity: '1', unit: 'tbsp' },
      { name: 'rice', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Smash cucumbers, toss with chili sauce, soy sauce, ginger, sesame oil, and seeds.',
      'Mix chickpea flour with water and scallions. Pan-fry pancakes until golden on both sides.',
      'Serve pancakes with smashed cucumbers and sliced avocado.',
    ],
    prepTime: '15 min',
    cookTime: '10 min',
    servings: 4,
    macrosPerServing: { calories: 340, protein_g: 14, carbs_g: 42, fat_g: 14 },
    tags: ['vegan', 'high-protein', 'gluten-free-adaptable'],
    notes: null,
  },
  {
    name: 'White Bean-Avocado Salad with Radish Salsa',
    source: 'Salad Seasons',
    category: 'dinner',
    ingredients: [
      { name: 'radishes', quantity: '6', unit: '' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'scallions', quantity: '3', unit: '' },
      { name: 'serrano pepper', quantity: '1', unit: '' },
      { name: 'limes', quantity: '2', unit: '' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'white beans (canned)', quantity: '2', unit: 'cans (15 oz)' },
      { name: 'avocado', quantity: '1', unit: 'large' },
    ],
    steps: [
      'Dice radishes, cilantro, scallions, and serrano. Mix with lime juice and olive oil for salsa.',
      'Drain and rinse white beans. Dice avocado.',
      'Toss beans and avocado with radish salsa. Season with salt.',
    ],
    prepTime: '15 min',
    cookTime: '0 min',
    servings: 4,
    macrosPerServing: { calories: 310, protein_g: 12, carbs_g: 34, fat_g: 16 },
    tags: ['vegan', 'high-fiber', 'anti-inflammatory'],
    notes: null,
  },

  // --- Glucose Goddess (14) ---
  {
    name: 'My Favorite San Francisco Salad',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'red onion', quantity: '1/2', unit: '' },
      { name: 'apple cider vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'chicken breast', quantity: '8', unit: 'oz' },
      { name: 'Greek yogurt', quantity: '1/4', unit: 'cup' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'grapefruit', quantity: '1', unit: '' },
      { name: 'kale', quantity: '3', unit: 'cups' },
      { name: 'Little Gem or romaine lettuce', quantity: '2', unit: 'heads' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Quick-pickle red onion in ACV. Season and cook chicken breast 6-7 min per side.',
      'Massage kale with olive oil. Segment grapefruit.',
      'Assemble: lettuce, kale, sliced chicken, grapefruit, pickled onion. Drizzle yogurt-dill dressing.',
    ],
    prepTime: '10 min',
    cookTime: '7 min',
    servings: 2,
    macrosPerServing: { calories: 380, protein_g: 34, carbs_g: 18, fat_g: 20 },
    tags: ['glucose-friendly', 'high-protein', 'gluten-free'],
    notes: null,
  },
  {
    name: 'Tahini Baked Cod',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'cod fillets', quantity: '2', unit: '6-oz' },
      { name: 'shallots', quantity: '2', unit: '' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: '' },
      { name: 'broccolini', quantity: '1', unit: 'bunch' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Toss sliced shallots and broccolini with olive oil on a sheet pan. Nestle cod fillets in.',
      'Spread tahini over cod, top with dill.',
      'Bake at 425°F for 12 min. Squeeze lemon over everything.',
    ],
    prepTime: '5 min',
    cookTime: '12 min',
    servings: 2,
    macrosPerServing: { calories: 360, protein_g: 36, carbs_g: 12, fat_g: 20 },
    tags: ['glucose-friendly', 'high-protein', 'anti-inflammatory'],
    notes: null,
  },
  {
    name: 'Grown-Up Tuna Pita',
    source: 'Glucose Goddess',
    category: 'lunch',
    ingredients: [
      { name: 'canned tuna', quantity: '1', unit: 'can (5 oz)' },
      { name: 'Dijon mustard', quantity: '1', unit: 'tsp' },
      { name: 'mayo', quantity: '1', unit: 'tbsp' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
      { name: 'pita bread', quantity: '1', unit: '' },
      { name: 'lettuce', quantity: '2', unit: 'leaves' },
    ],
    steps: [
      'Mix tuna with Dijon, mayo, and capers.',
      'Stuff into pita with lettuce.',
    ],
    prepTime: '10 min',
    cookTime: '0 min',
    servings: 1,
    macrosPerServing: { calories: 380, protein_g: 35, carbs_g: 28, fat_g: 14 },
    tags: ['quick-assembly', 'high-protein'],
    notes: null,
  },
  {
    name: 'Chickpea Peperonata with Rib-Eye Steak',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'onion', quantity: '1', unit: '' },
      { name: 'bell peppers', quantity: '2', unit: '' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'chickpeas (canned)', quantity: '1', unit: 'can (15 oz)' },
      { name: 'balsamic vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'rib-eye steaks', quantity: '2', unit: '8-oz' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion and peppers in olive oil with thyme and garlic until soft, 10 min.',
      'Add chickpeas and balsamic, cook 5 min more.',
      'Sear rib-eye steaks 4 min per side for medium. Rest 5 min, slice. Serve over peperonata.',
    ],
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 2,
    macrosPerServing: { calories: 620, protein_g: 52, carbs_g: 30, fat_g: 34 },
    tags: ['glucose-friendly', 'high-protein', 'gluten-free'],
    notes: null,
  },
  {
    name: 'Steamed Silken Tofu with Chile Garlic Ginger Sauce',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'silken tofu', quantity: '14', unit: 'oz' },
      { name: 'bok choy', quantity: '2', unit: 'heads' },
      { name: 'ginger', quantity: '1', unit: 'tbsp grated' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'soy sauce or tamari', quantity: '2', unit: 'tbsp' },
      { name: 'lime', quantity: '1', unit: '' },
      { name: 'chile powder', quantity: '1/2', unit: 'tsp' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Steam silken tofu and bok choy for 10-12 min.',
      'Sauté garlic and ginger in oil, add soy sauce, lime, chile powder for sauce.',
      'Serve tofu and bok choy over rice, drizzle sauce.',
    ],
    prepTime: '10 min',
    cookTime: '12 min',
    servings: 2,
    macrosPerServing: { calories: 380, protein_g: 18, carbs_g: 52, fat_g: 12 },
    tags: ['vegan-adaptable', 'anti-inflammatory', 'gluten-free-adaptable'],
    notes: null,
  },
  {
    name: 'Baked Salmon with Cucumber & Pickled Ginger Dressing',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'salmon fillets', quantity: '2', unit: '6-oz' },
      { name: 'pickled ginger', quantity: '2', unit: 'tbsp' },
      { name: 'cucumber', quantity: '1', unit: 'large' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'soy sauce or tamari', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Season salmon, bake at 400°F for 12 min.',
      'Dice cucumber, mix with pickled ginger, cilantro, soy sauce.',
      'Serve salmon over rice with cucumber dressing.',
    ],
    prepTime: '10 min',
    cookTime: '12 min',
    servings: 2,
    macrosPerServing: { calories: 480, protein_g: 38, carbs_g: 40, fat_g: 18 },
    tags: ['high-protein', 'anti-inflammatory', 'omega-3'],
    notes: null,
  },
  {
    name: 'Chicken Lemon & Olive Dish',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'bone-in chicken thighs', quantity: '4', unit: '' },
      { name: 'lemon', quantity: '1', unit: '' },
      { name: 'mixed olives', quantity: '1/2', unit: 'cup' },
      { name: 'red chile (optional)', quantity: '1', unit: '' },
      { name: 'broccolini', quantity: '1', unit: 'bunch' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sear chicken thighs skin-down in olive oil, 5 min.',
      'Add sliced lemon, olives, chile. Transfer to oven at 400°F for 30 min.',
      'Add broccolini for last 10 min of cooking.',
    ],
    prepTime: '7 min',
    cookTime: '35 min',
    servings: 2,
    macrosPerServing: { calories: 440, protein_g: 38, carbs_g: 8, fat_g: 30 },
    tags: ['batch-prep-friendly', 'glucose-friendly', 'gluten-free'],
    notes: null,
  },
  {
    name: 'Poached Chicken with Green Onion & Ginger',
    source: 'Glucose Goddess',
    category: 'dinner',
    ingredients: [
      { name: 'ginger', quantity: '2', unit: 'inches' },
      { name: 'green onions', quantity: '4', unit: '' },
      { name: 'chicken breasts', quantity: '2', unit: '6-oz' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'soy sauce or tamari', quantity: '3', unit: 'tbsp' },
      { name: 'quinoa or rice', quantity: '1', unit: 'cup' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Poach chicken breasts in water with ginger slices and garlic, 20 min. Let rest in broth.',
      'Make green onion-ginger sauce: mince green onions and ginger, heat olive oil, pour over. Add soy sauce.',
      'Slice chicken, serve over quinoa/rice with sauce.',
    ],
    prepTime: '7 min',
    cookTime: '20 min',
    servings: 2,
    macrosPerServing: { calories: 420, protein_g: 40, carbs_g: 36, fat_g: 14 },
    tags: ['high-protein', 'batch-prep-friendly'],
    notes: null,
  },
  {
    name: 'Toffee Peach Pavlova',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'egg whites', quantity: '4', unit: '' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'brown sugar', quantity: '2', unit: 'tbsp' },
      { name: 'white wine vinegar', quantity: '1', unit: 'tsp' },
      { name: 'Greek yogurt', quantity: '1', unit: 'cup' },
      { name: 'peaches', quantity: '3', unit: '' },
      { name: 'raspberries', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Beat egg whites to stiff peaks, gradually add sugar and vinegar. Shape on baking sheet.',
      'Bake at 250°F for 1.5 hrs. Let cool in oven.',
      'Top with Greek yogurt (not heavy cream — lactose), sliced peaches, and raspberries.',
    ],
    prepTime: '15 min',
    cookTime: '90 min',
    servings: 6,
    macrosPerServing: { calories: 180, protein_g: 5, carbs_g: 38, fat_g: 1 },
    tags: ['glucose-friendly-dessert'],
    notes: 'Use Greek yogurt not heavy cream (lactose intolerant adaptation)',
  },
  {
    name: 'Very Simple Chocolate Mousse',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'dark chocolate (70% cacao)', quantity: '4', unit: 'oz' },
      { name: 'eggs', quantity: '3', unit: '' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'berries', quantity: '1/2', unit: 'cup' },
      { name: 'yogurt', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Melt chocolate, let cool slightly. Separate eggs.',
      'Whisk yolks into chocolate. Beat whites with sugar to stiff peaks, fold in.',
      'Chill 2+ hrs. Serve with berries and yogurt.',
    ],
    prepTime: '25 min',
    cookTime: '0 min',
    servings: 4,
    macrosPerServing: { calories: 210, protein_g: 6, carbs_g: 18, fat_g: 14 },
    tags: ['glucose-friendly-dessert'],
    notes: null,
  },
  {
    name: 'Miso Chocolate Truffles',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'dark chocolate', quantity: '6', unit: 'oz' },
      { name: 'coconut cream', quantity: '1/3', unit: 'cup' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'miso', quantity: '1', unit: 'tbsp' },
      { name: 'hazelnuts', quantity: '1/4', unit: 'cup' },
      { name: 'cocoa powder', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat coconut cream (sub for heavy cream — lactose), pour over chopped chocolate. Stir until smooth.',
      'Mix in butter and miso. Chill until firm, 2+ hrs.',
      'Roll into balls, coat in cocoa powder. Omit maple syrup (nuts+sugar rule). Chopped hazelnuts optional on side only.',
    ],
    prepTime: '25 min',
    cookTime: '0 min',
    servings: 15,
    macrosPerServing: { calories: 90, protein_g: 1, carbs_g: 8, fat_g: 7 },
    tags: ['glucose-friendly-dessert'],
    notes: 'ADAPTED: coconut cream instead of heavy cream (lactose). Omit maple syrup — nuts+sugar reaction. Hazelnuts kept separate/optional.',
  },
  {
    name: 'Mixed Berry & Oat Crumble',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'sugar', quantity: '3', unit: 'tbsp' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'rolled oats', quantity: '1/3', unit: 'cup' },
      { name: 'frozen mixed berries', quantity: '3', unit: 'cups' },
      { name: 'Greek yogurt', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix flour, sugar, butter, and oats into crumbly topping (oat crumble replaces pistachios — nuts+sugar rule).',
      'Spread berries in baking dish, top with crumble.',
      'Bake at 375°F for 25 min. Serve with Greek yogurt.',
    ],
    prepTime: '10 min',
    cookTime: '25 min',
    servings: 4,
    macrosPerServing: { calories: 240, protein_g: 5, carbs_g: 36, fat_g: 10 },
    tags: ['glucose-friendly-dessert'],
    notes: 'ADAPTED: Oat crumble replaces pistachio crumble to avoid nuts+sugar combination.',
  },
  {
    name: 'Lemon Ricotta Cheesecake',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'lactose-free ricotta', quantity: '15', unit: 'oz' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'eggs', quantity: '3', unit: '' },
      { name: 'lemons', quantity: '2', unit: '' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
      { name: 'berries', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Mix lactose-free ricotta, sugar, flour, eggs, lemon zest + juice, and vanilla.',
      'Pour into greased pan, bake at 325°F for 40 min.',
      'Cool completely. Serve with fresh berries.',
    ],
    prepTime: '15 min',
    cookTime: '40 min',
    servings: 6,
    macrosPerServing: { calories: 220, protein_g: 10, carbs_g: 28, fat_g: 8 },
    tags: ['glucose-friendly-dessert'],
    notes: 'ADAPTED: Use lactose-free ricotta. Skip if unavailable.',
  },
  {
    name: 'Atomic Banana',
    source: 'Glucose Goddess',
    category: 'dessert',
    ingredients: [
      { name: 'banana', quantity: '1', unit: '' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'walnuts', quantity: '2', unit: 'tbsp' },
      { name: 'tahini (optional)', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Slice banana in half lengthwise. Sprinkle with cinnamon.',
      'Pan-sear in a dry skillet for 2 min until caramelized.',
      'Top with walnuts and tahini. Walnuts alone (no added sugar) = OK per nuts rule.',
    ],
    prepTime: '4 min',
    cookTime: '2 min',
    servings: 1,
    macrosPerServing: { calories: 240, protein_g: 5, carbs_g: 30, fat_g: 13 },
    tags: ['quick-assembly', 'gluten-free', 'vegan'],
    notes: 'Walnuts alone (no sugar) = OK per nuts+sugar rule.',
  },

  // --- Wellness/Plant-Based (4) ---
  {
    name: 'Grounding Sweet Beet Smoothie',
    source: 'Wellness/Plant-Based',
    category: 'smoothie',
    ingredients: [
      { name: 'kale', quantity: '1', unit: 'cup' },
      { name: 'beet (fresh)', quantity: '1', unit: 'small' },
      { name: 'frozen banana (whole)', quantity: '1', unit: '' },
      { name: 'plant protein powder', quantity: '1', unit: 'scoop' },
      { name: 'ground flaxseed', quantity: '1', unit: 'tbsp' },
      { name: 'almond butter', quantity: '1', unit: 'tbsp' },
      { name: 'unsweetened vanilla almond milk', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
      { name: 'ice', quantity: '1', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'sprinkle' },
    ],
    steps: [
      'Add kale + water first, blend until smooth.',
      'Add beet, banana, protein powder, flaxseed, almond butter, almond milk, and ice.',
      'Blend until smooth. Sprinkle cinnamon on top.',
    ],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    macrosPerServing: { calories: 380, protein_g: 28, carbs_g: 42, fat_g: 12 },
    tags: ['anti-inflammatory', 'vegan', 'high-protein-with-powder'],
    notes: "Jessica's notes: Add kale + water first, then blend. Use whole frozen banana. Sprinkle of cinnamon.",
  },
  {
    name: 'Pineapple Turmeric Sunshine Smoothie',
    source: 'Wellness/Plant-Based',
    category: 'smoothie',
    ingredients: [
      { name: 'celery', quantity: '1', unit: 'stalk' },
      { name: 'frozen pineapple', quantity: '1', unit: 'cup' },
      { name: 'ground turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'shredded coconut (unsweetened)', quantity: '1', unit: 'tbsp' },
      { name: 'plant protein powder', quantity: '1', unit: 'scoop' },
      { name: 'ginger', quantity: '1/2', unit: 'inch' },
      { name: 'tahini', quantity: '1', unit: 'tbsp' },
      { name: 'unsweetened vanilla almond milk', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
      { name: 'ice', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend until smooth and creamy.',
    ],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    macrosPerServing: { calories: 320, protein_g: 24, carbs_g: 36, fat_g: 10 },
    tags: ['anti-inflammatory', 'vegan'],
    notes: null,
  },
  {
    name: 'Mermaid Detox Spirulina Smoothie',
    source: 'Wellness/Plant-Based',
    category: 'smoothie',
    ingredients: [
      { name: 'kale (or spinach/dandelion greens)', quantity: '1', unit: 'cup' },
      { name: 'frozen mango', quantity: '1', unit: 'cup' },
      { name: 'cucumber', quantity: '1/2', unit: '' },
      { name: 'ginger', quantity: '1/2', unit: 'inch' },
      { name: 'spirulina', quantity: '1', unit: 'tsp' },
      { name: 'shredded coconut', quantity: '1', unit: 'tbsp' },
      { name: 'plant protein powder', quantity: '1', unit: 'scoop' },
      { name: 'coconut water', quantity: '1', unit: 'cup' },
      { name: 'ice', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Add all ingredients to blender.',
      'Blend until smooth.',
    ],
    prepTime: '5 min',
    cookTime: '0 min',
    servings: 1,
    macrosPerServing: { calories: 300, protein_g: 24, carbs_g: 40, fat_g: 6 },
    tags: ['vegan', 'anti-inflammatory'],
    notes: null,
  },
  {
    name: 'Deconstructed Mermaid Sushi Nori Bowl',
    source: 'Wellness/Plant-Based',
    category: 'lunch',
    ingredients: [
      { name: 'extra-firm tofu', quantity: '14', unit: 'oz' },
      { name: 'tamari', quantity: '2', unit: 'tbsp' },
      { name: 'rice vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'short-grain brown rice', quantity: '1', unit: 'cup' },
      { name: 'kale', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: '' },
      { name: 'avocado', quantity: '1', unit: '' },
      { name: 'maple syrup', quantity: '1', unit: 'tsp' },
      { name: 'nori seaweed sheets', quantity: '2', unit: '' },
      { name: 'pickled ginger', quantity: '2', unit: 'tbsp' },
      { name: 'green onion', quantity: '2', unit: '' },
      { name: 'sesame seeds', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Press and cube tofu, marinate in tamari + rice vinegar + maple syrup. Bake at 400°F for 20 min.',
      'Cook brown rice. Massage kale with a drizzle of tamari.',
      'Bowl: rice, kale, baked tofu, sliced cucumber, avocado, crumbled nori, pickled ginger, green onion, sesame seeds.',
    ],
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 2,
    macrosPerServing: { calories: 480, protein_g: 24, carbs_g: 56, fat_g: 20 },
    tags: ['vegan', 'batch-prep-friendly'],
    notes: null,
  },
];

const proteinPowders = [
  {
    name: 'Clear Protein',
    brand: 'Clean Simple',
    category: 'protein-powder' as const,
    nutritionPerServing: { calories: 90, protein_g: 20, carbs_g: 1, fat_g: 0, serving_size: '1', serving_unit: 'scoop' },
    flavor: 'Blue Bahama (coconut + blue raspberry)',
    notes: null,
  },
  {
    name: 'Zero Carb Protein',
    brand: 'Isopure',
    category: 'protein-powder' as const,
    nutritionPerServing: { calories: 100, protein_g: 25, carbs_g: 0, fat_g: 0, serving_size: '1', serving_unit: 'scoop' },
    flavor: 'Unflavored',
    notes: null,
  },
  {
    name: 'Organic Peanut Butter Powder',
    brand: 'PBfit',
    category: 'protein-powder' as const,
    nutritionPerServing: { calories: 60, protein_g: 7, carbs_g: 5, fat_g: 2, serving_size: '1.5', serving_unit: 'tbsp' },
    flavor: 'Peanut Butter',
    notes: 'Peanut = legume not tree nut, but flavor is nutty — avoid combining with sweeteners per nuts+sugar rule.',
  },
  {
    name: 'Just Plain Protein',
    brand: 'Just Ingredients',
    category: 'protein-powder' as const,
    nutritionPerServing: { calories: 100, protein_g: 22, carbs_g: 2, fat_g: 1, serving_size: '1', serving_unit: 'scoop' },
    flavor: 'Unflavored',
    notes: null,
  },
  {
    name: 'Chocolate Protein',
    brand: 'Just Ingredients',
    category: 'protein-powder' as const,
    nutritionPerServing: { calories: 100, protein_g: 24, carbs_g: 2, fat_g: 1, serving_size: '1', serving_unit: 'scoop' },
    flavor: 'Chocolate',
    notes: null,
  },
];

async function seed() {
  console.log('Seeding recipes...');

  // Check if already seeded
  const existing = await db.select().from(schema.recipes).limit(1);
  if (existing.length > 0) {
    console.log('Recipes already seeded, skipping.');
  } else {
    for (const r of recipes) {
      await db.insert(schema.recipes).values(r as any);
    }
    console.log(`Seeded ${recipes.length} recipes.`);
  }

  console.log('Seeding protein powders...');
  const existingPantry = await db.select().from(schema.userPantry).limit(1);
  if (existingPantry.length > 0) {
    console.log('Pantry already seeded, skipping.');
  } else {
    for (const p of proteinPowders) {
      await db.insert(schema.userPantry).values({
        userId: 1,
        ...p,
      } as any);
    }
    console.log(`Seeded ${proteinPowders.length} protein powders.`);
  }

  console.log('Seed complete!');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
